---
week: "04"
title: "W#04"
---

## Relational Data, Math: Sets and Functions, Programming Functions {.unnumbered}

Reconsider the Lecture Material, consider the Additional Readings and Material, and check the Achievements for yourself. Work on the Homework Projects reach out for help if you get stuck.

## Lecture Material

Slides: [Direct Link](../lectures/W{{< meta week >}}.qmd)

```{=html}
<iframe src="https://{{< var org.name >}}.github.io/Website/lectures/W{{< meta week >}}.html" frameborder="0" width="800" height="550" style="border:1px solid black;" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
```


Find the live recording in the [Course's Team's Recording Folder]({{< var teams.concepts.recording_folder_link >}}). 

## Additional Readings and Material  

Sections in [R for Data Science](http://r4ds.hadley.nz) 

 - [Ch 14: Strings](https://r4ds.hadley.nz/strings)
 - [Ch 19: Joins](https://r4ds.hadley.nz/joins)
 - [Ch 25: Functions](https://r4ds.hadley.nz/functions)
 - [Ch 26: Iteration](https://r4ds.hadley.nz/iteration)

## Achievements

You 

- [ ] know the difference between `NaN` and `NA`
- [ ] have used the `dplyr` functions `left_join`, and `full_join` to combine data frames
- [ ] know what is meant by primary and foreign key
- [ ] know the difference between a vector (ordered elements, duplicates possible) and a set (no order, no duplicates) and have used the functions `unique`, `union`, `intersect`, and `setdiff`
- [ ] can program a function with various arguments and default values
- [ ] can program a function which does a shift and scale transformation to data
- [ ] know about the value of vectorized functions for data operations
- [ ] have used the concept of the function `map` (for iteration over values of a list or vector) and `reduce` (for aggregation over values of a list or vector)

## Homework Projects Progress Guides

Find the Repositories of your Homework Projects in the Course's GitHub-Organization's [{{< var org.name >}} > Repositories](https://github.com/orgs/{{< var org.name >}}/repositories).

Project's INSTRUCTIONS you should have completed:   

**Project_NYCFlights**: 1., 2., 3., 4. 5., 6.   
**Project_COVID19**: 1.1, 1.2, **1.3, 1.4, 1.5**

::: {.callout-note}
Don't panic, if you fell behind, just do it later. Find your own learning path. Better step by step than randomly skipping things. It is about learning not just completing!
:::