---
week: "07"
title: "W#07"
---

## Models in Science, Linear Model, Nonlinear Models, Causal Inference {.unnumbered}

Reconsider the Lecture Material, consider the Additional Readings and Material, and check the Achievements for yourself. Work on the Homework Projects reach out for help if you get stuck.

## Lecture Material

Slides: [Direct Link](../lectures/W{{< meta week >}}.qmd)

```{=html}
<iframe src="https://{{< var org.name >}}.github.io/Website/lectures/W{{< meta week >}}.html" frameborder="0" width="800" height="550" style="border:1px solid black;" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
```

Input of Prof. Fabian Dehos on Causal Inference:

{{< pdf ../lectures/W07_Input_Dehos_Causal_Inference.pdf width=800 height=500 >}}

Find the live recording in the [Course's Team's Recording Folder]({{< var teams.concepts.recording_folder_link >}}). 

## Additional Readings and Material  

Read the following section in [Introduction to Modern Statistics](https://openintro-ims.netlify.app/):

- [Ch 8: Linear regression with multiple predictors](https://openintro-ims.netlify.app/model-mlr)


## Achievements
 
You

- [ ] can explain, and interpret the coefficients of a linear model
- [ ] can define and fit a linear model (in R and/or python)
- [ ] know which part of a linear model output relates to explanation and prediction 
- [ ] can explain what residuals are
- [ ] have an idea what "All models are wrong, but some are useful" means
- [ ] know the difference between the $\beta$'s (population parameters which we do not know) and the $\hat\beta$'s (the estimated parameters from the data) and how this relates to a *inferential* research questions
- [ ] know how the correlation of two variables relates to the slope of a linear model with one variable as predictor and the other as response variable (the slope is the correlation times the ratio of the standard deviations of the two variables)
- [ ] know how to interpret the $R^2$ of a linear model
- [ ] know what dummy variables are and how many you need for a categorical variable with $k$ levels
- [ ] can interpret the coefficients of a linear model with dummy variables as main effects, in particular you 
    - [ ] know what it means that the intercept is the mean of the reference category
    - [ ] know that the coefficient of a dummy variable is the difference of the mean of the category represented by the dummy variable and the mean of the reference category
- [ ] can identify examples of scatter plots where a linear model is bad
- [ ] can explain when log-transforming the response variable makes a linear model a good idea

## Homework Projects Progress Guides

Find the Repositories of your Homework Projects in the Course's GitHub-Organization's [{{< var org.name >}} > Repositories](https://github.com/orgs/{{< var org.name >}}/repositories).

Project's INSTRUCTIONS you should have completed:   

**Project_NYCFlights**: 1., 2., 3., 4. 5., 6., 7.    
**Project_COVID19**: 1.1, 1.2, 1.3, 1.4, 1.5, 2.1, 2.2 
**Project_DataScienceProfiles**: to come

::: {.callout-note}
Don't panic, if you fell behind, just do it later. Find your own learning path. Better step by step than randomly skipping things. It is about learning not just completing!
:::