project:
  type: website
  render:
    - index.qmd
    - schedule.qmd
    - setup.qmd
    - final.qmd
    - homework.qmd
    - literature.qmd
    - help.qmd
    - material/M01.qmd
    - material/M02.qmd
    - material/M03.qmd
    - material/M04.qmd
    - lectures/W02.qmd
    - lectures/W03.qmd
    - lectures/W04.qmd
    
execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Data Science Concepts / Data Science Tools"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
    right:
      - icon: github
        href: "{{< var org.link >}}"
        text: "{{< var org.name >}}" 
        
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Syllabus"
        file: index.qmd
      - section: Schedule 
        href: schedule.qmd
        contents:
          - material/M01.qmd
          - material/M02.qmd
          - material/M03.qmd
          - material/M04.qmd
      - setup.qmd
      - literature.qmd
      # - text: "Onboarding Late-arriving"
      #   file: late.qmd
      - homework.qmd
      - final.qmd
      - help.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true



