<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.33">

  <meta name="author" content="Jan Lorenz">
  <title>Data Science Concepts / Data Science Tools – W#08: Linear Model: Categorical Predictors, More Predictors, Interaction; Categorical Response, Logistic Regression</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-f563837468303362081e247dddd440d0.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">W#08: Linear Model: Categorical Predictors, More Predictors, Interaction; Categorical Response, Logistic Regression</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Jan Lorenz 
</div>
</div>
</div>

</section><section id="TOC">
<nav role="doc-toc"> 
<h2 id="toc-title">Table of contents</h2>
<ul>
<li><a href="#/linear-models-with-categorical-variables-as-predictors" id="/toc-linear-models-with-categorical-variables-as-predictors">Linear Models with Categorical Variables as Predictors</a></li>
<li><a href="#/linear-models-and-r-squared" id="/toc-linear-models-and-r-squared">Linear models and R-squared</a></li>
<li><a href="#/linear-models-with-more-predictors" id="/toc-linear-models-with-more-predictors">Linear models with more predictors</a></li>
<li><a href="#/interaction-effects" id="/toc-interaction-effects">Interaction Effects</a></li>
<li><a href="#/predicting-categorical-data" id="/toc-predicting-categorical-data">Predicting Categorical Data</a></li>
<li><a href="#/generalized-linear-models" id="/toc-generalized-linear-models">Generalized linear models</a></li>
<li><a href="#/logistic-regression" id="/toc-logistic-regression">Logistic regression</a></li>
<li><a href="#/sensitivity-and-specificity" id="/toc-sensitivity-and-specificity">Sensitivity and specificity</a></li>
<li><a href="#/prediction" id="/toc-prediction">Prediction</a></li>
</ul>
</nav>
</section>
<section id="preliminaries" class="slide level2">
<h2>Preliminaries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb1-3"><a></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb1-4"><a></a><span class="fu">library</span>(openintro)</span>
<span id="cb1-5"><a></a><span class="fu">library</span>(patchwork) <span class="co"># For pasting ggplots together</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="recap-linear-model" class="slide level2 smaller" data-background-color="aquamarine">
<h2>Recap: Linear Model</h2>
<p>We fit a linear model predicting <code>flipper_length_mm</code> from <code>body_mass_g</code> using least squares regression. In R:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = flipper_length_mm ~ body_mass_g, data = penguins)

Coefficients:
(Intercept)  body_mass_g  
  136.72956      0.01528  </code></pre>
</div>
</div>
<p>As equation: average <code>flipper_length_mm</code> <span class="math inline">\(= 137 + 0.0153\cdot\)</span> <code>body_mass_g</code></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a>pengmod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g, <span class="at">data =</span> penguins)</span>
<span id="cb3-4"><a></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb3-5"><a></a>  <span class="fu">bind_cols</span>(<span class="fu">predict</span>(pengmod, penguins)) <span class="sc">|&gt;</span></span>
<span id="cb3-6"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(body_mass_g, flipper_length_mm)) <span class="sc">+</span></span>
<span id="cb3-7"><a></a>  <span class="fu">geom_segment</span>(</span>
<span id="cb3-8"><a></a>    <span class="fu">aes</span>(</span>
<span id="cb3-9"><a></a>      <span class="at">x =</span> body_mass_g,</span>
<span id="cb3-10"><a></a>      <span class="at">y =</span> flipper_length_mm,</span>
<span id="cb3-11"><a></a>      <span class="at">xend =</span> body_mass_g,</span>
<span id="cb3-12"><a></a>      <span class="at">yend =</span> .pred</span>
<span id="cb3-13"><a></a>    ),</span>
<span id="cb3-14"><a></a>    <span class="at">color =</span> <span class="st">"gray"</span></span>
<span id="cb3-15"><a></a>  ) <span class="sc">+</span></span>
<span id="cb3-16"><a></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb3-17"><a></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb3-18"><a></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> .pred), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb3-19"><a></a>  <span class="fu">geom_point</span>(</span>
<span id="cb3-20"><a></a>    <span class="at">data =</span> <span class="fu">tibble</span>(</span>
<span id="cb3-21"><a></a>      <span class="at">x =</span> <span class="fu">mean</span>(penguins<span class="sc">$</span>body_mass_g, <span class="at">na.rm =</span> T),</span>
<span id="cb3-22"><a></a>      <span class="at">y =</span> <span class="fu">mean</span>(penguins<span class="sc">$</span>flipper_length_mm, <span class="at">na.rm =</span> T)</span>
<span id="cb3-23"><a></a>    ),</span>
<span id="cb3-24"><a></a>    <span class="at">mapping =</span> <span class="fu">aes</span>(x, y),</span>
<span id="cb3-25"><a></a>    <span class="at">color =</span> <span class="st">"green"</span>,</span>
<span id="cb3-26"><a></a>    <span class="at">size =</span> <span class="dv">5</span></span>
<span id="cb3-27"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="W08_files/figure-revealjs/unnamed-chunk-3-1.png" width="960" class="r-stretch"></section>
<section>
<section id="linear-models-with-categorical-variables-as-predictors" class="title-slide slide level1 center">
<h1>Linear Models with Categorical Variables as Predictors</h1>

</section>
<section id="categorical-variables-as-predictors" class="slide level2">
<h2>Categorical variables as predictors?</h2>
<p>When a variable has categories the entries are not numbers. Can we use it as predictors?</p>
<div class="fragment">
<p>Let’s explore and just try what happens with <code>species</code> as explanatory variable:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> species, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb4-4"><a></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term             estimate std.error statistic   p.value
  &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)        190.       0.540    351.   0        
2 speciesChinstrap     5.87     0.970      6.05 3.79e-  9
3 speciesGentoo       27.2      0.807     33.8  1.84e-110</code></pre>
</div>
</div>
<p>Remember, we have three species: Adelie, Chinstrap, Gentoo. What happened?</p>
</div>
<div class="fragment">
<p>Two of the three species categories appear as variables now.</p>
<ul>
<li>Categorical variables are automatically encoded as <strong>dummy variables</strong></li>
<li>Each coefficient describes the expected difference between flipper length of that particular species compared to the baseline level</li>
<li>What is the baseline level? <span class="fragment"><span style="color:red;">The first category!</span> (Here alphabetically <code>"Adelie"</code>)</span></li>
</ul>
</div>
</section>
<section id="how-do-dummy-variables-look" class="slide level2">
<h2>How do dummy variables look?</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>species</th>
<th>speciesChinstrap</th>
<th>speciesGentoo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Adelie</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Adelie</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Chinstrap</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td>Gentoo</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Gentoo</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td>Gentoo</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Adelie</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Chinstrap</td>
<td>1</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>Then the fitting of the linear model is as before using variables which just have 0’s and 1’s as entries. (In machine learning called <em>one-hot encoding</em>)</p>
</section>
<section id="check-create-dummies-ourselves" class="slide level2">
<h2>Check: Create Dummies ourselves</h2>
<div class="columns">
<div class="column">
<p>Create dummy variables with <code>if_else</code> and show three example rows, one for each species:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>penguins_with_dummies <span class="ot">&lt;-</span> penguins <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-3"><a></a>    <span class="at">speciesChinstrap =</span> <span class="fu">if_else</span>(species <span class="sc">==</span> <span class="st">"Chinstrap"</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb6-4"><a></a>    <span class="at">speciesGentoo =</span> <span class="fu">if_else</span>(species <span class="sc">==</span> <span class="st">"Gentoo"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb6-5"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb6-6"><a></a>  <span class="fu">select</span>(flipper_length_mm, speciesChinstrap, speciesGentoo)</span>
<span id="cb6-7"><a></a>penguins_with_dummies <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">1</span>, <span class="dv">200</span>, <span class="dv">300</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  flipper_length_mm speciesChinstrap speciesGentoo
              &lt;int&gt;            &lt;dbl&gt;         &lt;dbl&gt;
1               181                0             0
2               225                0             1
3               193                1             0</code></pre>
</div>
</div>
</div><div class="column">
<p>Fit the model manually:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a>penguins_with_dummies <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a></a>  <span class="fu">lm</span>(flipper_length_mm <span class="sc">~</span> speciesChinstrap <span class="sc">+</span> speciesGentoo, <span class="at">data =</span> _)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = flipper_length_mm ~ speciesChinstrap + speciesGentoo, 
    data = penguins_with_dummies)

Coefficients:
     (Intercept)  speciesChinstrap     speciesGentoo  
          189.95              5.87             27.23  </code></pre>
</div>
</div>
</div></div>
<p>Equation:<br>
average <code>flipper_length_mm</code> <span class="math inline">\(= \beta_0 + \beta_1\cdot\)</span> <code>speciesChinstrap</code> <span class="math inline">\(+ \beta_2\cdot\)</span> <code>speciesGentoo</code><br>
With fitted parameters <span class="math inline">\(\beta_0 \approx 190, \beta_1 \approx 5.87\)</span> and <span class="math inline">\(\beta_2 = 27.2\)</span></p>

<aside><div>
<p>Coding notes: With <code>lm</code> we use the linear model engine directly without the tidymodels pipeline. With <code>data = _</code> we use the data that is piped in. The <code>_</code> is a placeholder for the piped data. We need it because <code>lm</code> does not have a <code>data</code> argument in the first position. (<code>lm</code> is older than the tidyverse and does not support piping directly.)</p>
</div></aside></section>
<section id="interpretation" class="slide level2 smaller" data-background-color="khaki">
<h2>Interpretation</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> species, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb10-4"><a></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term             estimate std.error statistic   p.value
  &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)        190.       0.540    351.   0        
2 speciesChinstrap     5.87     0.970      6.05 3.79e-  9
3 speciesGentoo       27.2      0.807     33.8  1.84e-110</code></pre>
</div>
</div>
<ul>
<li>Flipper length of the baseline species is the intercept.
<ul>
<li>Average flipper length of Adelie is 190 mm</li>
</ul></li>
<li>Flipper length of the two other species add their coefficient
<ul>
<li>Average flipper length of Chinstrap is 190 + 5.87 mm</li>
<li>Average flipper length of Gentoo is 190 + 27.2 mm</li>
</ul></li>
</ul>
</section>
<section id="compare-to-a-visualization" class="slide level2 smaller">
<h2>Compare to a visualization</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term             estimate std.error statistic   p.value
  &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)        190.       0.540    351.   0        
2 speciesChinstrap     5.87     0.970      6.05 3.79e-  9
3 speciesGentoo       27.2      0.807     33.8  1.84e-110</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a>jitterplots <span class="ot">&lt;-</span> penguins <span class="sc">|&gt;</span> </span>
<span id="cb13-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(species, flipper_length_mm)) <span class="sc">+</span></span>
<span id="cb13-3"><a></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb13-4"><a></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">"red"</span>)</span>
<span id="cb13-5"><a></a>boxplots <span class="ot">&lt;-</span> penguins <span class="sc">|&gt;</span></span>
<span id="cb13-6"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(species, flipper_length_mm)) <span class="sc">+</span></span>
<span id="cb13-7"><a></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb13-8"><a></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">"red"</span>)</span>
<span id="cb13-9"><a></a>jitterplots <span class="sc">+</span> boxplots</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="W08_files/figure-revealjs/unnamed-chunk-9-1.png" width="960" class="r-stretch"><p>The red dots are the mean values for species.</p>
</section></section>
<section>
<section id="linear-models-and-r-squared" class="title-slide slide level1 center">
<h1>Linear models and R-squared</h1>

</section>
<section id="quality-of-different-linear-models" class="slide level2 smaller">
<h2>Quality of different linear models?</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept) 137.      2.00          68.5 5.71e-201
2 body_mass_g   0.0153  0.000467      32.7 4.37e-107</code></pre>
</div>
</div>
<p>average <code>flipper_length_mm</code> <span class="math inline">\(= 137 + 0.0153\cdot\)</span> <code>body_mass_g</code></p>
<div class="fragment">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a></a>  <span class="fu">fit</span>(bill_depth_mm <span class="sc">~</span> bill_length_mm, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb16-4"><a></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term           estimate std.error statistic  p.value
  &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)     20.9       0.844      24.7  4.72e-78
2 bill_length_mm  -0.0850    0.0191     -4.46 1.12e- 5</code></pre>
</div>
</div>
<p>average <code>bill_depth_mm</code> <span class="math inline">\(= 20.9 -0.085\cdot\)</span> <code>bill_length_mm</code></p>
</div>
<div class="fragment">
<p><strong>Technical:</strong> The idea of the <code>tidy()</code> function is to turn an object into a tidy tibble. Here, it extracts the coefficients of the linear model (and more statistical information).</p>
</div>
</section>
<section id="r-squared-of-a-fitted-model" class="slide level2 smaller" data-background-color="aquamarine">
<h2>R-squared of a fitted model</h2>
<p><span class="math inline">\(R^2\)</span> is the percentage of variability in the response explained by the regression model.</p>
<p>R-squared is also called <strong>coefficient of determination</strong>.</p>
<p><strong>Definition</strong>:</p>
<p><span class="math inline">\(R^2 = 1 - \frac{SS_\text{res}}{SS_\text{tot}}\)</span></p>
<p>where <span class="math inline">\(SS_\text{res} = \sum_i(y_i - f_i)^2 = \sum_i e_i^2\)</span> is the <em>sum of the squared residuals</em>, and<br>
<span class="math inline">\(SS_\text{tot} = \sum_i(y_i - \bar y)^2\)</span> the <em>total sum of squares</em> which is proportional to the variance of <span class="math inline">\(y\)</span>. (<span class="math inline">\(\bar y\)</span> is the mean of <span class="math inline">\(y\)</span>.)</p>

<img data-src="https://upload.wikimedia.org/wikipedia/commons/8/86/Coefficient_of_Determination.svg" class="r-stretch"></section>
<section id="linear-model-r-squared" class="slide level2 smaller">
<h2>Linear model R-squared</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb18-4"><a></a>  <span class="fu">glance</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.759         0.758  6.91     1071. 4.37e-107     1 -1146. 2297. 2309.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p>The command <code>glance</code> shows summary statistics of model fits in a single row.</p>
<p><strong>Interpretation R-squared?</strong> 75.9% of the variance of flipper length can be explained by a linear relation with body mass. <span class="fragment" style="color:red;">Warning: “Explain” <span class="math inline">\(\neq\)</span> causal claim!</span></p>
<div class="fragment">
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a></a>  <span class="fu">fit</span>(bill_depth_mm <span class="sc">~</span> bill_length_mm, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb20-4"><a></a>  <span class="fu">glance</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1    0.0552        0.0525  1.92      19.9 0.0000112     1  -708. 1422. 1433.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p>5.52% of the variance of bill depth can be explained by a linear relation with bill length.</p>
</div>
</section>
<section id="r-squared-and-correlation" class="slide level2 smaller">
<h2>R-squared and correlation</h2>
<p>For a linear model with one predictor, the square of the correlation coefficient is the same as the R-squared of the model. Hence, the name <span class="math inline">\(R^2\)</span>! Check with code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb22-4"><a></a>  <span class="fu">glance</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.759         0.758  6.91     1071. 4.37e-107     1 -1146. 2297. 2309.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a><span class="fu">cor</span>(</span>
<span id="cb24-2"><a></a>  penguins<span class="sc">$</span>flipper_length_mm,</span>
<span id="cb24-3"><a></a>  penguins<span class="sc">$</span>body_mass_g,</span>
<span id="cb24-4"><a></a>  <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span></span>
<span id="cb24-5"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8712018</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a><span class="fu">cor</span>(</span>
<span id="cb26-2"><a></a>  penguins<span class="sc">$</span>flipper_length_mm,</span>
<span id="cb26-3"><a></a>  penguins<span class="sc">$</span>body_mass_g,</span>
<span id="cb26-4"><a></a>  <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span></span>
<span id="cb26-5"><a></a>)<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7589925</code></pre>
</div>
</div>
</section></section>
<section>
<section id="linear-models-with-more-predictors" class="title-slide slide level1 center">
<h1>Linear models with more predictors</h1>
<ul>
<li>Hey, we had already two predictors created all of a sudden when we were using a categorical variable with 3 categories</li>
<li>We can also add more numerical predictors</li>
</ul>
</section>
<section id="add-predictors-to-more-coefficients" class="slide level2 smaller">
<h2>Add predictors <span class="math inline">\(\to\)</span> More coefficients</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb28-4"><a></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept) 137.      2.00          68.5 5.71e-201
2 body_mass_g   0.0153  0.000467      32.7 4.37e-107</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g <span class="sc">+</span> bill_length_mm, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb30-4"><a></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term           estimate std.error statistic   p.value
  &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    122.      2.86         42.7  1.70e-138
2 body_mass_g      0.0131  0.000545     23.9  7.56e- 75
3 bill_length_mm   0.549   0.0801        6.86 3.31e- 11</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a></a>  <span class="fu">fit</span>(</span>
<span id="cb32-4"><a></a>    flipper_length_mm <span class="sc">~</span> body_mass_g <span class="sc">+</span> bill_length_mm <span class="sc">+</span> bill_depth_mm,</span>
<span id="cb32-5"><a></a>    <span class="at">data =</span> penguins</span>
<span id="cb32-6"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb32-7"><a></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term           estimate std.error statistic   p.value
  &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    158.      4.63         34.1  1.80e-111
2 body_mass_g      0.0109  0.000538     20.3  1.93e- 60
3 bill_length_mm   0.592   0.0717        8.26 3.42e- 15
4 bill_depth_mm   -1.68    0.181        -9.29 1.99e- 18</code></pre>
</div>
</div>
</section>
<section id="more-predictors-glance-r-squared" class="slide level2 smaller">
<h2>More predictors: <code>glance</code> R-squared</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb34-4"><a></a>  <span class="fu">glance</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.759         0.758  6.91     1071. 4.37e-107     1 -1146. 2297. 2309.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb36-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g <span class="sc">+</span> bill_length_mm, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb36-4"><a></a>  <span class="fu">glance</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.788         0.787  6.49      631. 4.88e-115     2 -1123. 2255. 2270.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb38-3"><a></a>  <span class="fu">fit</span>(</span>
<span id="cb38-4"><a></a>    flipper_length_mm <span class="sc">~</span> body_mass_g <span class="sc">+</span> bill_length_mm <span class="sc">+</span> bill_depth_mm,</span>
<span id="cb38-5"><a></a>    <span class="at">data =</span> penguins</span>
<span id="cb38-6"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb38-7"><a></a>  <span class="fu">glance</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.831         0.830  5.80      556. 2.99e-130     3 -1084. 2179. 2198.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
</section>
<section id="more-predictors-equations" class="slide level2 smaller">
<h2>More predictors: Equations</h2>
<p>average <code>flipper_length_mm</code> <span class="math inline">\(= 137 + 0.0153\cdot\)</span> <code>body_mass_g</code><br>
75.9% explained variance</p>
<p>average <code>flipper_length_mm</code> <span class="math inline">\(= 122 + 0.0131\cdot\)</span> <code>body_mass_g</code> <span class="math inline">\(+ 0.549\cdot\)</span> <code>bill_length_mm</code><br>
78.8% explained variance</p>
<p>average <code>flipper_length_mm</code> <span class="math inline">\(= 158 + 0.0109\cdot\)</span> <code>body_mass_g</code> <span class="math inline">\(+ 0.592\cdot\)</span> <code>bill_length_mm</code> <span class="math inline">\(- 1.68\cdot\)</span> <code>bill_length_mm</code><br>
83.1% explained variance</p>
<p>Often more predictors bring higher R-squared. However, doing it blindly makes interpretation complicated and can lead to <strong>overfitting</strong>! (Treated later.)</p>
</section></section>
<section>
<section id="interaction-effects" class="title-slide slide level1 center">
<h1>Interaction Effects</h1>
<p>Adding products of variables as new variable.</p>
</section>
<section id="categorical-variable-as-main-effect" class="slide level2 smaller">
<h2>Categorical variable as main effect</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g <span class="sc">+</span> species, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb40-4"><a></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term              estimate std.error statistic   p.value
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)      159.       2.39         66.6  2.45e-196
2 body_mass_g        0.00840  0.000634     13.3  1.40e- 32
3 speciesChinstrap   5.60     0.788         7.10 7.33e- 12
4 speciesGentoo     15.7      1.09         14.4  6.80e- 37</code></pre>
</div>
</div>
<p>A <strong>main effect</strong> by categorical dummy variables allows for different intercepts per species. (However, the slopes are the same.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb42-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g <span class="sc">+</span> species, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb42-4"><a></a>  <span class="fu">glance</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.854         0.853  5.40      659. 7.42e-141     3 -1060. 2129. 2149.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p>Adding species increases R-squared better than adding bill length and bill depth together!</p>
</section>
<section id="adding-as-interaction-effect" class="slide level2 smaller">
<h2>Adding as interaction effect</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb44-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g <span class="sc">*</span> species, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb44-4"><a></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  term                          estimate std.error statistic   p.value
  &lt;chr&gt;                            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)                  165.       3.55         46.5  1.56e-148
2 body_mass_g                    0.00668  0.000952      7.01 1.30e- 11
3 speciesChinstrap             -13.9      7.30         -1.90 5.84e-  2
4 speciesGentoo                  6.06     6.05          1.00 3.17e-  1
5 body_mass_g:speciesChinstrap   0.00523  0.00195       2.68 7.66e-  3
6 body_mass_g:speciesGentoo      0.00236  0.00135       1.75 8.16e-  2</code></pre>
</div>
</div>
<ul>
<li>Note the <code>*</code> for interaction effect!</li>
<li>Also main effects for both variables are in as coefficients.</li>
<li>Adelie is the baseline species (because it is first in the alphabet).</li>
<li>An <strong>interaction effect</strong> allows for different slopes for each species!</li>
</ul>
</section>
<section id="regression-lines-by-species" class="slide level2 smaller">
<h2>Regression lines by species</h2>

<img data-src="W08_files/figure-revealjs/unnamed-chunk-26-1.png" width="960" class="r-stretch"><p>Compare the slopes to the regression output on the slides before!</p>
</section>
<section id="different-equations-for-each-species" class="slide level2 smaller">
<h2>Different equations for each species!</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb46-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g <span class="sc">*</span> species, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb46-4"><a></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  term                          estimate std.error statistic   p.value
  &lt;chr&gt;                            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)                  165.       3.55         46.5  1.56e-148
2 body_mass_g                    0.00668  0.000952      7.01 1.30e- 11
3 speciesChinstrap             -13.9      7.30         -1.90 5.84e-  2
4 speciesGentoo                  6.06     6.05          1.00 3.17e-  1
5 body_mass_g:speciesChinstrap   0.00523  0.00195       2.68 7.66e-  3
6 body_mass_g:speciesGentoo      0.00236  0.00135       1.75 8.16e-  2</code></pre>
</div>
</div>
<p>Adelie:<br>
average <code>flipper_length_mm</code> <span class="math inline">\(= 165 + 0.00668\cdot\)</span> <code>body_mass_g</code></p>
<p>Chinstrap:<br>
average <code>flipper_length_mm</code> <span class="math inline">\(= 165 - 13.6 + (0.00668 + 0.00523)\cdot\)</span> <code>body_mass_g</code></p>
<p>Gentoo:<br>
average <code>flipper_length_mm</code> <span class="math inline">\(= 165 + 6.06 + (0.00668 + 0.00236)\cdot\)</span> <code>body_mass_g</code></p>
</section>
<section id="improvement-of-interaction-effects-is-small-here" class="slide level2 smaller">
<h2>Improvement of interaction effects is small here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g <span class="sc">+</span> species, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb48-4"><a></a>  <span class="fu">glance</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.854         0.853  5.40      659. 7.42e-141     3 -1060. 2129. 2149.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb50-3"><a></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g <span class="sc">*</span> species, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb50-4"><a></a>  <span class="fu">glance</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.857         0.855  5.35      404. 9.60e-140     5 -1056. 2125. 2152.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
</section>
<section id="interaction-effects-of-two-categoricals" class="slide level2 smaller">
<h2>Interaction effects of two categoricals</h2>
<p>Assume <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> are categorical variables. We add their product in the linear model as a <em>new variable</em>: <span class="math inline">\(y_i = \beta_0 + \beta_1x_1  + \beta_2x_2 + \beta_{3}x_1x_2 + \dots\)</span>.</p>
<p><strong>Example:</strong> <span class="math inline">\(x_1\)</span> is <em>gender female</em> and <span class="math inline">\(x_2\)</span> <em>having kids</em></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a></a><span class="fu">tibble</span>(<span class="at">gender_female =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">has_kids =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">|&gt;</span></span>
<span id="cb52-2"><a></a>  <span class="fu">mutate</span>(<span class="at">gender_female_x_has_kids =</span> gender_female <span class="sc">*</span> has_kids) <span class="sc">|&gt;</span></span>
<span id="cb52-3"><a></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">gender_female</th>
<th style="text-align: right;">has_kids</th>
<th style="text-align: right;">gender_female_x_has_kids</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>What is the baseline? <span class="fragment"><em>Being male without kids.</em></span></li>
<li>Thought experiment: When we estimate a model explaining life satisfaction with these. How would we see if being a mother increases life satisfaction more than being a father? <span class="fragment"><em>positive coefficient for <code>gender_female_x_has_kids</code></em></span></li>
</ul>
</section></section>
<section>
<section id="predicting-categorical-data" class="title-slide slide level1 center">
<h1>Predicting Categorical Data</h1>
<p>Large part of the content adapted from <a href="http://datasciencebox.org" class="uri">http://datasciencebox.org</a>.</p>
</section>
<section id="what-if-response-is-binary" class="slide level2 smaller">
<h2>What if response is binary?</h2>
<ul>
<li>Example: <strong>Spam filter</strong> for emails</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a></a><span class="fu">glimpse</span>(email) <span class="co"># Part of the openintro data package</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,921
Columns: 21
$ spam         &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ to_multiple  &lt;fct&gt; 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ from         &lt;fct&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ cc           &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 2, 1, 0, 2, 0, …
$ sent_email   &lt;fct&gt; 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, …
$ time         &lt;dttm&gt; 2012-01-01 07:16:41, 2012-01-01 08:03:59, 2012-01-01 17:…
$ image        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ attach       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ dollar       &lt;dbl&gt; 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 5, 0, 0, …
$ winner       &lt;fct&gt; no, no, no, no, no, no, no, no, no, no, no, no, no, no, n…
$ inherit      &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ viagra       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ password     &lt;dbl&gt; 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, …
$ num_char     &lt;dbl&gt; 11.370, 10.504, 7.773, 13.256, 1.231, 1.091, 4.837, 7.421…
$ line_breaks  &lt;int&gt; 202, 202, 192, 255, 29, 25, 193, 237, 69, 68, 25, 79, 191…
$ format       &lt;fct&gt; 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, …
$ re_subj      &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, …
$ exclaim_subj &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, …
$ urgent_subj  &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ exclaim_mess &lt;dbl&gt; 0, 1, 6, 48, 1, 1, 1, 18, 1, 0, 2, 1, 0, 10, 4, 10, 20, 0…
$ number       &lt;fct&gt; big, small, small, small, none, none, big, small, small, …</code></pre>
</div>
</div>
</section>
<section id="multinomial-response-variable" class="slide level2">
<h2>Multinomial response variable?</h2>
<ul>
<li>We will not cover other categorical variables than binary ones here.</li>
<li>However, many of the probabilistic concepts transfer.</li>
</ul>
</section>
<section id="email-example-variables" class="slide level2 smaller">
<h2>Email Example: Variables</h2>
<p><code>?email</code> shows all variable descriptions. For example:</p>
<ul>
<li><code>spam</code> Indicator for whether the email was spam.</li>
<li><code>from</code> Whether the message was listed as from anyone (this is usually set by default for regular outgoing email).</li>
<li><code>cc</code> Number of people cc’ed.</li>
<li><code>time</code> Time at which email was sent.</li>
<li><code>attach</code> The number of attached files.</li>
<li><code>dollar</code> The number of times a dollar sign or the word “dollar” appeared in the email.</li>
<li><code>num_char</code> The number of characters in the email, in thousands.</li>
<li><code>re_subj</code> Whether the subject started with “Re:”, “RE:”, “re:”, or “rE:”</li>
</ul>

<aside><div>
<p>The development, extraction, or discovery of such variables is called <strong>feature engineering</strong>, <strong>feature extraction</strong> or <strong>feature discovery</strong>. Usually, a combination of <em>domain knowledge</em> and <em>data science</em> skill is needed to do this.</p>
</div></aside></section>
<section id="email-example-data-exploration" class="slide level2 smaller">
<h2>Email Example: Data exploration</h2>
<p>Would you expect spam to be longer or shorter?</p>
<div class="fragment">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a></a>email <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> num_char, <span class="at">y =</span> spam)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="W08_files/figure-revealjs/unnamed-chunk-32-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="fragment">
<p>Would you expect spam subject to start with “Re:” or the like?</p>
</div>
<div class="fragment">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a></a>email <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> re_subj, <span class="at">fill =</span> spam)) <span class="sc">+</span> <span class="fu">geom_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="W08_files/figure-revealjs/unnamed-chunk-33-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="linear-models" class="slide level2 smaller">
<h2>Linear models?</h2>
<p>Both seem to give some signal. <strong>How can we model the relationship?</strong></p>
<p>We focus first on just <code>num_char</code>:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a></a>email <span class="sc">|&gt;</span></span>
<span id="cb57-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> num_char, <span class="at">y =</span> <span class="fu">as.numeric</span>(spam) <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb57-3"><a></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb57-4"><a></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="W08_files/figure-revealjs/unnamed-chunk-34-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<p>We would like to have a better concept!</p>

<aside><div>
<p>Why do we need <code>y = as.numeric(spam)-1</code> instead of just <code>y = spam</code>?? Answer: <code>spam</code> is a factor although it looks like a numeric variable. The underlying integers for the two categories <code>"0"</code> and <code>"1"</code> are <code>1</code> and <code>2</code>. The strange form transforms the factor into a numerical variables with the values <code>0</code> and <code>1</code> as we need it for a target variable in a linear model.</p>
</div></aside></section>
<section id="a-penguins-example---predict-sex" class="slide level2 smaller">
<h2>A penguins example - predict sex</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb58-2"><a></a>  <span class="fu">na.omit</span>() <span class="sc">|&gt;</span></span>
<span id="cb58-3"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> body_mass_g, <span class="at">y =</span> <span class="fu">as.numeric</span>(sex) <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb58-4"><a></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb58-5"><a></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="W08_files/figure-revealjs/unnamed-chunk-35-1.png" width="960" class="r-stretch"><p><span style="color:red;">It does not make much sense to predict 0-1-values with a linear model.</span></p>
</section>
<section id="a-probabilistic-concept" class="slide level2 smaller" data-background-color="aquamarine">
<h2>A probabilistic concept</h2>
<ul>
<li>We treat each outcome (spam and not) as successes and failures arising from separate Bernoulli trials
<ul>
<li><strong>Bernoulli trial:</strong> a random experiment with exactly two possible outcomes, <em>success</em> and <em>failure</em>, in which the <em>probability of success</em> is the same every time the experiment is conducted</li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li>Each email is treated as Bernoulli trial with separate probability of success</li>
</ul>
<p><span class="math display">\[ y_i ∼ \text{Bernoulli}(p_i) \]</span></p>
</div>
<div class="fragment">
<ul>
<li>We use the predictor variables to model the Bernoulli parameter <span class="math inline">\(p_i\)</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Now we conceptualized a continuous response, but still a linear model does not fit perfectly for <span class="math inline">\(p_i\)</span> (since a probability is between 0 and 1).</li>
<li>However, we can transform the linear model to have the appropriate range.</li>
</ul>
</div>
</section></section>
<section>
<section id="generalized-linear-models" class="title-slide slide level1 center">
<h1>Generalized linear models</h1>

</section>
<section id="characterising-glms" class="slide level2 smaller" data-background-color="aquamarine">
<h2>Characterising GLMs</h2>
<ul>
<li><strong>Generalized linear models (GLMs)</strong> are a way of addressing many problems in regression</li>
<li>Logistic regression is one example</li>
</ul>
<p>All GLMs have the following three characteristics:</p>
<ol type="1">
<li>A <strong>probability distribution</strong> as a generative model for the outcome variable <span class="math inline">\(y_i \sim \text{Distribution}(\text{parameter})\)</span></li>
</ol>
<div class="fragment">
<ol start="2" type="1">
<li>A <strong>linear model</strong> <span class="math inline">\(\eta = \beta_0 + \beta_1 X_1 + \cdots + \beta_k X_k\)</span><br>
where <span class="math inline">\(\eta\)</span> is related to a mean parameter of the distribution by the …</li>
</ol>
</div>
<div class="fragment">
<ol start="3" type="1">
<li><strong>Link function</strong> that relates the linear model to the parameter of the outcome distribution.</li>
</ol>
</div>
</section></section>
<section>
<section id="logistic-regression" class="title-slide slide level1 center">
<h1>Logistic regression</h1>

</section>
<section id="logistic-regression-1" class="slide level2 smaller" data-background-color="aquamarine">
<h2>Logistic regression</h2>
<ul>
<li><strong>Logistic regression</strong> is a GLM used to model a binary categorical outcome using numerical and categorical predictors.</li>
<li>The <em>distribution</em> is the Bernoulli distribution with parameter <span class="math inline">\(p\)</span> (success probability).</li>
<li>As <em>link function</em> connecting <span class="math inline">\(\eta_i\)</span> to <span class="math inline">\(p_i\)</span> we use the <strong>logit function</strong>.</li>
</ul>
<div class="fragment">
<ul>
<li><strong>Logit function:</strong> <span class="math inline">\(\text{logit}: [0,1] \to \mathbb{R}\)</span></li>
</ul>
<p><span class="math display">\[\text{logit}(p) = \log\left(\frac{p}{1-p}\right)\]</span></p>
<ul>
<li><span class="math inline">\(\frac{p}{1-p}\)</span> is called the <strong>odds</strong> of a success which happens with probability <span class="math inline">\(p\)</span>.<br>
Example: Roll a six with a die has <span class="math inline">\(p=1/6\)</span>. Thus, the odds are <span class="math inline">\(\frac{1/6}{5/6} = 1/5\)</span>. Sometimes written as 1:5. <em>“The odds of success are one to five.”</em></li>
</ul>
</div>
</section>
<section id="properties-of-the-logit" class="slide level2 smaller" data-background-color="aquamarine">
<h2>Properties of the logit</h2>
<ul>
<li>Logit takes values between 0 and 1 and returns values between <span class="math inline">\(-\infty\)</span> and <span class="math inline">\(\infty\)</span></li>
<li>The inverse of the logit function if the <strong>logistic function</strong> (mapping values from <span class="math inline">\(-\infty\)</span> and <span class="math inline">\(\infty\)</span> to values between 0 and 1): <span class="math display">\[\text{logit}^{-1}(x) = \text{logistic}(x) = \frac{e^x}{1+e^x} = \frac{1}{1+e^{-x}}\]</span></li>
<li>Logit can be interpreted as the log odds of a success – more on this later.</li>
</ul>

<aside><div>
<ul>
<li>The logistic function is the solution of the differential equation <span class="math inline">\(\frac{d}{dx}f(x) = f(x)(1-f(x))\)</span> which also appears in the SI-model of epidemics (and other models of exponential growth with saturation).</li>
<li>Good exercises to check your math skills:
<ol type="1">
<li>Show that <span class="math inline">\(\text{logit}^{-1}(x) = \text{logistic}(x)\)</span> or the other way round.</li>
<li>Transform <span class="math inline">\(\frac{e^x}{1+e^x}\)</span> into <span class="math inline">\(\frac{1}{1+e^{-x}}\)</span>.</li>
<li>Check that <span class="math inline">\(\text{logistic}(x)\)</span> is a solution to <span class="math inline">\(\frac{d}{dx}f(x) = f(x)(1-f(x))\)</span>.</li>
</ol></li>
<li>You can request hints from me when you get stuck.</li>
</ul>
</div></aside></section>
<section id="logit-and-logistic-function" class="slide level2 smaller" data-background-color="aquamarine">
<h2>Logit and <span style="color:red;">logistic</span> function</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb59-2"><a></a>  <span class="fu">geom_function</span>(</span>
<span id="cb59-3"><a></a>    <span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fu">log</span>(x <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> x)),</span>
<span id="cb59-4"><a></a>    <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">0.001</span>, <span class="fl">0.999</span>),</span>
<span id="cb59-5"><a></a>    <span class="at">n =</span> <span class="dv">500</span></span>
<span id="cb59-6"><a></a>  ) <span class="sc">+</span></span>
<span id="cb59-7"><a></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>x)), <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb59-8"><a></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">1</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">5</span>)) <span class="sc">+</span></span>
<span id="cb59-9"><a></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">1</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">5</span>)) <span class="sc">+</span></span>
<span id="cb59-10"><a></a>  <span class="fu">coord_fixed</span>() <span class="sc">+</span></span>
<span id="cb59-11"><a></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">24</span>) <span class="sc">+</span></span>
<span id="cb59-12"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"x"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="W08_files/figure-revealjs/unnamed-chunk-36-1.png" width="960" class="r-stretch"></section>
<section id="the-logistic-regression-model" class="slide level2" data-background-color="aquamarine">
<h2>The logistic regression model</h2>
<ul>
<li>Based on the three GLM criteria we have
<ul>
<li><span class="math inline">\(y_i \sim \text{Bernoulli}(p_i)\)</span></li>
<li><span class="math inline">\(\eta_i = \beta_0+\beta_1 x_{1,i} + \cdots + \beta_n x_{n,i}\)</span></li>
<li><span class="math inline">\(\text{logit}(p_i) = \eta_i\)</span></li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li>From which we get</li>
</ul>
<p><span class="math display">\[p_i = \frac{e^{\beta_0+\beta_1 x_{1,i} + \cdots + \beta_k x_{k,i}}}{1 + e^{\beta_0+\beta_1 x_{1,i} + \cdots + \beta_k x_{k,i}}}\]</span></p>
</div>
</section>
<section id="modeling-spam" class="slide level2 smaller">
<h2>Modeling spam</h2>
<p>With <code>tidymodels</code> we fit a GLM in the same way as a linear model except we</p>
<ul>
<li>specify the model with <code>logistic_reg()</code></li>
<li>use <code>"glm"</code> instead of <code>"lm"</code> as the engine</li>
<li>define <code>family = "binomial"</code> for the link function to be used in the model</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a></a>spam_fit <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb60-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"glm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb60-3"><a></a>  <span class="fu">fit</span>(spam <span class="sc">~</span> num_char, <span class="at">data =</span> email, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb60-4"><a></a><span class="fu">tidy</span>(spam_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)  -1.80     0.0716     -25.1  2.04e-139
2 num_char     -0.0621   0.00801     -7.75 9.50e- 15</code></pre>
</div>
</div>

<aside><div>
<ul>
<li>The family is <em>binomial</em> because the Bernoulli distribution is a special case of the binomial distribution <span class="math inline">\(\text{Binomial}(n,p)\)</span> with <span class="math inline">\(n=1\)</span>.</li>
<li>The binomial distribution specifies the probability to have <span class="math inline">\(k\)</span> successes in <span class="math inline">\(n\)</span> Bernoulli trials with the same success probability <span class="math inline">\(p\)</span>.</li>
</ul>
</div></aside></section>
<section id="spam-model" class="slide level2 smaller">
<h2>Spam model</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)  -1.80     0.0716     -25.1  2.04e-139
2 num_char     -0.0621   0.00801     -7.75 9.50e- 15</code></pre>
</div>
</div>
<p>Model: <span class="math display">\[\log\left(\frac{p}{1-p}\right) = -1.80-0.0621\cdot \text{num_char}\]</span></p>
</section>
<section id="predicted-probability-examples" class="slide level2 smaller">
<h2>Predicted probability: Examples</h2>
<p>We can compute the <strong>predicted probability</strong> that an email with 2000 character is spam as follows:</p>
<p><span class="math display">\[\log\left(\frac{p}{1-p}\right) = -1.80-0.0621\cdot 2 = -1.9242\]</span></p>
<p>(Note: <code>num_char</code> is in thousands.)</p>
<p><span class="math display">\[\frac{p}{1-p} = e^{-1.9242} = 0.15 \Rightarrow p = 0.15 \cdot (1 - p)\]</span></p>
<p><span class="math display">\[p = 0.15 - 0.15\cdot p \Rightarrow 1.15\cdot p = 0.15\]</span></p>
<p><span class="math display">\[p = 0.15 / 1.15 = 0.13\]</span></p>
</section>
<section id="predicted-probability" class="slide level2 smaller">
<h2>Predicted probability</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a></a>logistic <span class="ot">&lt;-</span> <span class="cf">function</span>(t) <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>t))</span>
<span id="cb63-2"><a></a>preds <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">15</span>, <span class="dv">40</span>), <span class="at">y =</span> <span class="fu">logistic</span>(<span class="sc">-</span><span class="fl">1.80</span> <span class="sc">-</span> <span class="fl">0.0621</span> <span class="sc">*</span> x))</span>
<span id="cb63-3"><a></a>email <span class="sc">|&gt;</span></span>
<span id="cb63-4"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> num_char, <span class="at">y =</span> <span class="fu">as.numeric</span>(spam) <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb63-5"><a></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb63-6"><a></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fu">logistic</span>(<span class="sc">-</span><span class="fl">1.80</span> <span class="sc">-</span> <span class="fl">0.0621</span> <span class="sc">*</span> x), <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb63-7"><a></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> preds, <span class="at">mapping =</span> <span class="fu">aes</span>(x, y), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="W08_files/figure-revealjs/unnamed-chunk-39-1.png" width="960" class="r-stretch"><p>Spam probability 2,000 characters: 0.1273939<br>
Spam probability 15,000 characters: 0.06114<br>
Spam probability 40,000 characters: 0.0135999</p>
</section>
<section id="interpretation-of-coefficients" class="slide level2 smaller">
<h2>Interpretation of coefficients</h2>
<p><span class="math display">\[\log\left(\frac{p}{1-p}\right) = -1.80-0.0621\cdot \text{num_char}\]</span></p>
<p>What does an increase by thousand characters (<code>num_char + 1</code>) imply?</p>
<div class="fragment">
<p>Let us assume the predicted probability of an email is <span class="math inline">\(p_0\)</span>. Then an increase of <code>num_char</code> by one implied that the log-odds become</p>
<p><span class="math display">\[\log\left(\frac{p_0}{1-p_0}\right) - 0.0621 = \log\left(\frac{p_0}{1-p_0}\right) - \log(e^{0.0621})\]</span></p>
<p><span class="math display">\[ = \log\left(\frac{p_0}{1-p_0}\right) + \log(\frac{1}{e^{0.0621}}) = \log\left(\frac{p_0}{1-p_0} \frac{1}{e^{0.0621}}\right) = \log\left(\frac{p_0}{1-p_0} 0.94\right)\]</span></p>
<p>That means the odds of being spam decrease by 6%.</p>
</div>
</section>
<section id="penguins-example" class="slide level2 smaller">
<h2>Penguins example</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb64-2"><a></a>sex_fit <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb64-3"><a></a>  <span class="fu">set_engine</span>(<span class="st">"glm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb64-4"><a></a>  <span class="fu">fit</span>(sex <span class="sc">~</span> body_mass_g, <span class="at">data =</span> <span class="fu">na.omit</span>(penguins), <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb64-5"><a></a><span class="fu">tidy</span>(sex_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept) -5.16     0.724        -7.13 1.03e-12
2 body_mass_g  0.00124  0.000173      7.18 7.10e-13</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a></a><span class="fu">na.omit</span>(penguins) <span class="sc">|&gt;</span></span>
<span id="cb66-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> body_mass_g, <span class="at">y =</span> sex)) <span class="sc">+</span></span>
<span id="cb66-3"><a></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb66-4"><a></a>  <span class="fu">geom_function</span>(</span>
<span id="cb66-5"><a></a>    <span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fu">logistic</span>(<span class="sc">-</span><span class="fl">5.16</span> <span class="sc">+</span> <span class="fl">0.00124</span> <span class="sc">*</span> x) <span class="sc">+</span> <span class="dv">1</span>,</span>
<span id="cb66-6"><a></a>    <span class="at">color =</span> <span class="st">"red"</span></span>
<span id="cb66-7"><a></a>  ) <span class="sc">+</span></span>
<span id="cb66-8"><a></a>  <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="dv">2000</span>, <span class="dv">7000</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="W08_files/figure-revealjs/unnamed-chunk-41-1.png" width="960" class="r-stretch"></section>
<section id="summarizing-the-idea-of-logistic-regression" class="slide level2 smaller">
<h2>Summarizing the Idea of Logistic Regression</h2>
<ul>
<li>We want to explain/predict a binary response variable.</li>
<li>We want to use the concept of linear models.</li>
<li>To that end we first interprete each outcome as the outcome of a probabilisitic event happening with probability <span class="math inline">\(p_i\)</span>. That way we transform the problem from modeling a binary outcome to a numerical outcome.</li>
<li>However, probabilities are bounded between 0 and 1.</li>
<li>We use the logit function to map probabilities to the real line. That means we predict the log-odds of the probability.</li>
<li>We model the log-odds with a linear model.</li>
</ul>
</section></section>
<section>
<section id="sensitivity-and-specificity" class="title-slide slide level1 center">
<h1>Sensitivity and specificity</h1>
<ul>
<li>Two performance measures for a prediction model with binary outcome.</li>
<li>Also called a “binary classifier.</li>
<li>Today, just the idea.</li>
</ul>
</section>
<section id="false-positive-and-negative" class="slide level2 smaller">
<h2>False positive and negative</h2>
<table class="caption-top">
<colgroup>
<col style="width: 28%">
<col style="width: 35%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Email labelled spam</th>
<th>Email labelled not spam</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Email is spam</strong></td>
<td>True positive</td>
<td>False negative (Type 2 error)</td>
</tr>
<tr class="even">
<td><strong>Email is not spam</strong></td>
<td>False positive (Type 1 error)</td>
<td>True negative</td>
</tr>
</tbody>
</table>
</section>
<section id="confusion-matrix" class="slide level2">
<h2>Confusion matrix</h2>
<p>More general: <a href="https://en.wikipedia.org/wiki/Confusion_matrix"><strong>Confusion matrix</strong></a> of statistical classification:</p>

<img data-src="img/confusion_small.png" class="r-stretch"></section>
<section id="sensitivity-and-specificity-1" class="slide level2 smaller">
<h2>Sensitivity and specificity</h2>
<div class="columns">
<div class="column" style="width:40%;">
<p><img data-src="img/confusion_small.png"></p>
</div><div class="column" style="width:60%;">
<p><strong>Sensitivity</strong> is the <em>true positive rate</em>: TP / (TP + FN)<br>
<strong>Specificity</strong> is the <em>true negative rate</em>: TN / (TN + FP)</p>
</div></div>
<p>For spam a <em>positive</em> case is an email labelled as <em>spam</em>:</p>
<p><strong>Sensitivity:</strong> Fraction of emails <em>labelled as</em> spam among all emails which <em>are</em> spam.<br>
Low sensitivity <span class="math inline">\(\to\)</span> More false negatives <span class="math inline">\(\to\)</span> More spam in you inbox!</p>
<p><strong>Specificity:</strong> Fraction of emails <em>labelled as not</em> spam among all emails which <em>are not</em> spam.<br>
Low specificity <span class="math inline">\(\to\)</span> More false positives <span class="math inline">\(\to\)</span> More relevant emails in spam folder!</p>
<div class="fragment">
<p>If you were designing a spam filter, would you want sensitivity and specificity to be high or low? What are the trade-offs associated with each decision?</p>
</div>
</section>
<section id="covid-19-tests" class="slide level2 smaller">
<h2>COVID-19 tests</h2>
<p>A COVID-19 test is called <em>positive</em> when it indicates the presence of the virus.</p>
<p><em>What is the sensitivity of a test?</em></p>
<div class="fragment">
<p>Probability the test is positive when the tested person has COVID-19. (The true positive rate.)</p>
</div>
<div class="fragment">
<p><em>What is the specificity of a test?</em></p>
</div>
<div class="fragment">
<p>Probability the test is negative when the tested person does not have COVID-19. (The true negative rate.)</p>
<p>Often the sensitivity is around 90% and the specificity is around 99%. What does that mean?</p>
</div>
<div class="fragment">
<ul>
<li>When you do not have COVID the test is more likely to be correct, than when you do have COVID. However, specificity and sensitivity do not tell something about the probability to have COVID when the test is positive, or to not have COVID when the test is negative.</li>
</ul>
</div>
</section>
<section id="another-view" class="slide level2">
<h2>Another view</h2>

<img data-src="https://upload.wikimedia.org/wikipedia/commons/5/5a/Sensitivity_and_specificity_1.01.svg" class="r-stretch"></section></section>
<section>
<section id="prediction" class="title-slide slide level1 center">
<h1>Prediction</h1>

</section>
<section id="prediction-vs.-explanation" class="slide level2 smaller">
<h2>Prediction vs.&nbsp;Explanation</h2>
<p><strong>Explanation</strong> and <strong>Prediction</strong> are different <strong>Modelling Mindsets</strong><sup>1</sup>.</p>
<ul>
<li>With an <em>Explanatory Mindset</em> we want to understand the relationship between the predictors and the outcome.
<ul>
<li>We interpret coefficients</li>
<li>We ask what variance can be explained by a linear model or a PCA</li>
</ul></li>
<li>With a <em>Predictive Mindset</em> we want to predict the outcome for new observations.
<ul>
<li>We use the model to predict the outcome for new observations</li>
<li>We ask how well we can predict the outcome for new observations</li>
<li>We may ignore why the model works</li>
</ul></li>
</ul>
<p>Important: The mindsets are very different but they may use the same models!</p>


<aside><ol class="aside-footnotes"><li id="fn1"><p>From Molnar, C. (2022). Modeling mindsets: The many cultures of learning from data. Christoph Molnar c/o Mucbook Clubhouse.</p></li></ol></aside></section></section>

    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="img/ConstructorUniversity.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>MDSSB-DSCO-02: Data Science Concepts</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: true,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/CU-F25-MDSSB-01-Concepts-Tools\.github\.io\/Website\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>