---
title: "W#14"
author: Jan Lorenz
format: 
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: true
    preview-links: true
    logo: img/ConstructorUniversity.png
    footer: "[CU-F23-MDSSB-DSCO-02: Data Science Concepts](https://github.com/CU-F23-MDSSB-01-Concepts-Tools)"
bibliography: "/home/janlo/Documents/literature/litlorenz_zot.bib"
---

```{r}
#| include: false
library(tidyverse)
library(palmerpenguins)
library(tidymodels)
library(openintro)
```

## Today

1. A note on synthetic data sets
2. Timeline to finish the semester
3. Course Goals
4. Mock Exam
5. Students evaluation of teaching (SET)


## Synthetic data sets {.smaller}

- **Synthetic data sets** are data sets that are generated by a computer program
- They are used to test algorithms and to illustrate concepts
- They are also used to **protect privacy of real data sets**

**For data science project:**

- Better use real data
- From synthetic data it is very hard to learn about the real world
- Interpretation of results with respect to the real world is very limited
- Theoretical insights are often very generic

## Timeline to finish the semester {.smaller }

- Today: **Monday, Dec 4**
- **Thursday, Final Tools Session:** Work-in-progress presentation of your Data Science Projects
- **This week:** Feedback on Homework repositories shall be prepares by instructors. 
- **By Sunday, Dec 10:** Write your questions on the achievements of the course for the exam to me (Email or Teams).
- **Monday, Dec 11:** I will answer your questions in the organization repo. 
- **Friday Dec 15:** Receive final information on the exam by email or Teams.  Project
- **Saturday, Dec 16, 9:00-11:00:** Final exam
- **Friday, Dec 22:** Push your final commits for the Data Science Project


## Course Goals  {.smaller}

1. Enable you to **do data analysis projects** on your own
2. Enable you to **learn on your own**
    - analysis concepts 
    - programming tools
    - being aware of relevant domain knowledge
    - communicate your results in reproducible reports
    
## Next courses with me  {.smaller}

**Spring 2024**

- Data Science Lab
- Introduction to Computational Social Science

**Fall 2024**

- Visual Communication and Data Storytelling

## Mock Exam  {.smaller}

- Discuss questions in groups of 2-3 students
- Question round


## Students evaluation of teaching (SET)

- Fill out the survey for this course (you have received access by email)
   - It is anonymous, we will not see personalized evaluations
- We, the instructors, are very interested to read your feedback
   - All 3 instructors will share the feedback
